### PR TITLE
Adding tables post

### PR DESCRIPTION
**Pull request by apreshill**
issue #5

### CODE REVIEW

**Comment by yihui** [comment]
I guess it is time to teach you `git rebase` now :)

**Comment by apreshill** [comment]
Haha ok baby is in bed and I am ready- in my defense, I missed a step in my [cheatsheet](https://www.canva.com/design/DACbDf6Bmzg/share?role=EDITOR&token=lATwlvXHWh0uva4cnD32yg&utm_content=DACbDf6Bmzg&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton) 😄 But I don't know how to fix now that I did it!

**Comment by yihui** [comment]
Wow, you fixed it! That is amazing. I'm glad that I don't need to draw a tree graph to explain it to you now.

Next time make sure to work on new branches instead of always pushing to the master branch, and remember that new branches should typically be created based on the master branch (it is easy to make the mistake of creating one feature branch based on another feature branch that you are currently working on).

**Review by yihui — APPROVED** [review]

**Comment by apreshill** [comment]
Seriously I did? No way- I was ready for some pain tonight. Calls for a celebration :wine_glass: :cocktail:

**Comment by yihui** [comment]
The problem has two solutions (rebase or merge), and you happen to have hit one of them (merge).

**Pull request merged**
